### PR TITLE
change unmaintained to warn

### PR DESCRIPTION
**Pull request by mikeyoung85**

### CODE REVIEW

**Review by havocp — APPROVED** [review]

**Comment by mikeyoung85** [comment]
Will need @katzj help to push a new release

**Comment by katzj** [comment]
Can do!

Also fyi, we can just make depci depend on a git hash and not need a release like we've done for bibliothecary

**Comment by mikeyoung85** [comment]
v0.5.1 tag is pushed up

**Comment by katzj** [comment]
Pushed

**Pull request merged**
